const W={E:0,M:189,F:150,C:77};
const T={E:'Empty',M:'Male',F:'Female',C:'Child'};
const arms=[135,165,195,225,254];
const sample=[['M','M','F'],['M','F','E'],['M','F','E'],['M','F','E'],['E','E','E']];
let seats=sample.map(r=>r.slice());
function el(id){return document.getElementById(id)}
function n(id){const v=parseFloat(el(id).value);return Number.isFinite(v)?v:0}
function f(x,d=0){return Number(x).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d})}
function buildRows(){const root=el('rows');root.innerHTML='';for(let r=0;r<5;r++){const row=document.createElement('div');row.className='row';row.innerHTML=`<div class="rt"><span>Row ${r+1} <span class="small">Arm ${arms[r]}</span></span><span id="rt${r}">0 lb</span></div><div class="seats"></div>`;const seatWrap=row.querySelector('.seats');for(let s=0;s<3;s++){const seat=document.createElement('div');seat.className='seat';seat.innerHTML=`<div class="sn">Seat ${s+1}</div><div class="choices"></div>`;const chs=seat.querySelector('.choices');['E','M','F','C'].forEach(k=>{const c=document.createElement('div');c.className='ch';c.dataset.r=r;c.dataset.s=s;c.dataset.v=k;c.textContent=T[k];c.onclick=()=>{seats[r][s]=k;render();calc()};chs.appendChild(c)});seatWrap.appendChild(seat)}root.appendChild(row)}}
function render(){document.querySelectorAll('.ch').forEach(c=>c.classList.toggle('on',seats[+c.dataset.r][+c.dataset.s]===c.dataset.v));for(let r=0;r<5;r++){el('rt'+r).textContent=f(seats[r].reduce((a,k)=>a+W[k],0))+' lb'}}
function calc(){const dow=n('dow'),doi=n('doi'),block=n('block'),trip=n('trip');const paxRows=seats.map(row=>row.reduce((a,k)=>a+W[k],0));let pax=paxRows.reduce((a,b)=>a+b,0);let paxMom=paxRows.reduce((a,w,i)=>a+w*arms[i],0);const st=n('stretcher');pax+=st;paxMom+=st*224.7;const areaA=paxRows[0]+paxRows[1],areaB=paxRows[2]+paxRows[3],areaC=paxRows[4]+st;const bagD=n('bagD'),bagAft=n('bagAft'),bagShelf=n('bagShelf'),bagR5=n('bagR5'),bagR4=n('bagR4');const bag=bagD+bagAft+bagShelf+bagR5+bagR4;const bagMom=bagD*302+bagAft*354+bagShelf*391+bagR5*254+bagR4*225;const payload=pax+bag;const zfw=dow+payload;const tof=block-50;const lf=tof-trip;const tow=zfw+tof;const lw=tow-trip;const dowArm=(((doi-10)*10000)/dow)+210;const dowMom=dowArm*dow;function cg(w,fuel){const m=dowMom+paxMom+bagMom+fuel*201.7;const arm=w?m/w:0;return{arm,index:(((arm-210)*w)/10000)+10,mac:((arm-207.74)*1.282)+25}}const to=cg(tow,tof),la=cg(lw,lf);el('paxTotal').textContent=f(pax)+' lb';el('areas').textContent=`${f(areaA)} / ${f(areaB)} / ${f(areaC)}`;el('paxMoment').textContent=f(paxMom);el('bagTotal').textContent=f(bag)+' lb';el('payload').textContent=f(payload)+' lb';el('zfw').textContent=f(zfw)+' lb';el('remain').textContent=f(12500-tow)+' lb';el('tof').textContent=f(tof)+' lb';el('tow').textContent=f(tow)+' lb';el('toArm').textContent=f(to.arm,2);el('toIndex').textContent=f(to.index,4);el('toMac').textContent=f(to.mac,2)+'%';el('lf').textContent=f(lf)+' lb';el('lw').textContent=f(lw)+' lb';el('laArm').textContent=f(la.arm,2);el('laIndex').textContent=f(la.index,4);el('laMac').textContent=f(la.mac,2)+'%';let w=[];if(tow>12500)w.push('Takeoff weight is above 12,500 lb.');if(lf<0)w.push('Landing fuel is negative.');if(tow<=12500&&12500-tow<100)w.push('Close to 12,500 lb limit.');if(!w.length)w.push('Basic weight checks look okay. Verify CG envelope against approved data.');el('warn').textContent=w.join(' ')}
function resetSample(){seats=sample.map(r=>r.slice());['dow','doi','block','trip','stretcher','bagD','bagAft','bagShelf','bagR5','bagR4'].forEach(id=>{const defaults={dow:9142,doi:13.8,block:1450,trip:380,stretcher:0,bagD:260,bagAft:144,bagShelf:0,bagR5:0,bagR4:0};el(id).value=defaults[id]});render();calc()}
function clearSeats(){seats=Array.from({length:5},()=>['E','E','E']);render();calc()}
window.addEventListener('DOMContentLoaded',()=>{buildRows();render();calc();el('badge').textContent='✅ Live calculator active';el('resetBtn').onclick=resetSample;el('clearBtn').onclick=clearSeats;document.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc));if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}});
