const W={E:0,M:189,F:150,C:77},T={E:'Empty',M:'Male',F:'Female',C:'Child'},arms=[135,165,195,225,254];
const sample=[['M','M','F'],['M','F','E'],['M','F','E'],['M','F','E'],['E','E','E']];
const D={dow:9142,doi:13.8,block:1450,trip:380,stretcher:0,bagD:260,bagAft:144,bagShelf:0,bagR5:0,bagR4:0};
let seats=sample.map(r=>r.slice());
function el(id){return document.getElementById(id)}
function n(id){let v=parseFloat(el(id).value);return isFinite(v)?v:0}
function f(x,d=0){return Number(x).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d})}
function setv(id,v){el(id).value=String(v);el(id).defaultValue=String(v)}
function buildRows(){let root=el('rows');root.innerHTML='';for(let r=0;r<5;r++){let row=document.createElement('div');row.className='row';row.innerHTML='<div class="rt"><span>Row '+(r+1)+' <span class="small">Arm '+arms[r]+'</span></span><span id="rt'+r+'">0 lb</span></div><div class="seats"></div>';let wrap=row.querySelector('.seats');for(let s=0;s<3;s++){let seat=document.createElement('div');seat.className='seat';seat.innerHTML='<div class="sn">Seat '+(s+1)+'</div><div class="choices"></div>';let chs=seat.querySelector('.choices');['E','M','F','C'].forEach(k=>{let c=document.createElement('div');c.className='ch';c.dataset.r=r;c.dataset.s=s;c.dataset.v=k;c.textContent=T[k];c.onclick=function(){seats[r][s]=k;render();calc()};chs.appendChild(c)});wrap.appendChild(seat)}root.appendChild(row)}}
function render(){document.querySelectorAll('.ch').forEach(c=>c.classList.toggle('on',seats[+c.dataset.r][+c.dataset.s]===c.dataset.v));for(let r=0;r<5;r++)el('rt'+r).textContent=f(seats[r].reduce((a,k)=>a+W[k],0))+' lb'}
function calc(){let dow=n('dow'),doi=n('doi'),block=n('block'),trip=n('trip');let pr=seats.map(row=>row.reduce((a,k)=>a+W[k],0));let pax=pr.reduce((a,b)=>a+b,0),pm=pr.reduce((a,w,i)=>a+w*arms[i],0);let st=n('stretcher');pax+=st;pm+=st*224.7;let aA=pr[0]+pr[1],aB=pr[2]+pr[3],aC=pr[4]+st;let bd=n('bagD'),ba=n('bagAft'),bs=n('bagShelf'),br5=n('bagR5'),br4=n('bagR4');let bag=bd+ba+bs+br5+br4,bm=bd*302+ba*354+bs*391+br5*254+br4*225;let payload=pax+bag,zfw=dow+payload,tof=block-50,lf=tof-trip,tow=zfw+tof,lw=tow-trip;let da=(((doi-10)*10000)/dow)+210,dm=da*dow;function cg(w,fuel){let m=dm+pm+bm+fuel*201.7,arm=w?m/w:0;return{arm:arm,index:(((arm-210)*w)/10000)+10,mac:((arm-207.74)*1.282)+25}}let to=cg(tow,tof),la=cg(lw,lf);el('paxTotal').textContent=f(pax)+' lb';el('areas').textContent=f(aA)+' / '+f(aB)+' / '+f(aC);el('paxMoment').textContent=f(pm);el('bagTotal').textContent=f(bag)+' lb';el('payload').textContent=f(payload)+' lb';el('zfw').textContent=f(zfw)+' lb';el('remain').textContent=f(12500-tow)+' lb';el('tof').textContent=f(tof)+' lb';el('tow').textContent=f(tow)+' lb';el('toArm').textContent=f(to.arm,2);el('toIndex').textContent=f(to.index,4);el('toMac').textContent=f(to.mac,2)+'%';el('lf').textContent=f(lf)+' lb';el('lw').textContent=f(lw)+' lb';el('laArm').textContent=f(la.arm,2);el('laIndex').textContent=f(la.index,4);el('laMac').textContent=f(la.mac,2)+'%';let w=[];if(tow>12500)w.push('Takeoff weight is above 12,500 lb.');if(lf<0)w.push('Landing fuel is negative.');if(tow<=12500&&12500-tow<100)w.push('Close to 12,500 lb limit.');if(!w.length)w.push('Basic weight checks look okay. Verify CG envelope against approved data.');el('warn').textContent=w.join(' ')}
function resetSample(){seats=sample.map(r=>r.slice());Object.keys(D).forEach(id=>setv(id,D[id]));render();calc()}
function clearSeats(){seats=[['E','E','E'],['E','E','E'],['E','E','E'],['E','E','E'],['E','E','E']];render();calc()}
window.addEventListener('DOMContentLoaded',function(){buildRows();resetSample();el('badge').textContent='✅ Live calculator active v2';el('resetBtn').onclick=resetSample;el('clearBtn').onclick=clearSeats;document.querySelectorAll('input').forEach(i=>i.oninput=calc);if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});