const W={E:0,M:189,F:150,C:77},T={E:'–',M:'M',F:'F',C:'C'},arms=[135,165,195,225,254];
const emptySeats=[['E','E','E'],['E','E','E'],['E','E','E'],['E','E','E'],['E','E','E']];
const D={reg:'',dow:0,doi:0,block:0,trip:0,stretcher:0,bagD:0,bagAft:0,bagShelf:0,bagR5:0,bagR4:0};
const PRESET_KEY='dhc6_aircraft_presets_v1';
let seats=emptySeats.map(r=>r.slice());
let suggestedSeats=null;
function el(id){return document.getElementById(id)}
function n(id){let v=parseFloat(el(id).value);return isFinite(v)?v:0}
function f(x,d=0){return Number(x).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d})}
function setv(id,v){if(!el(id))return;el(id).value=String(v);el(id).defaultValue=String(v)}
function setText(id,txt){let x=el(id);if(x)x.textContent=txt}
function presets(){try{return JSON.parse(localStorage.getItem(PRESET_KEY)||'{}')}catch(e){return {}}}
function savePresets(p){localStorage.setItem(PRESET_KEY,JSON.stringify(p))}
function refreshPresetList(){let sel=el('presetSelect');if(!sel)return;let p=presets(),current=sel.value;sel.innerHTML='<option value="">Select aircraft preset</option>';Object.keys(p).sort().forEach(reg=>{let o=document.createElement('option');o.value=reg;o.textContent=reg+' — DOW '+p[reg].dow+' / DOI '+p[reg].doi;sel.appendChild(o)});if(p[current])sel.value=current}
function savePreset(){let reg=el('reg').value.trim().toUpperCase();let dow=n('dow'),doi=n('doi');if(!reg){setText('presetMsg','Enter aircraft registration first.');return}if(dow<=0||doi===0){setText('presetMsg','Enter current DOW and DOI before saving preset.');return}if(dow>12500){setText('presetMsg','DOW looks too high for DHC-6. Check extra zeros before saving preset.');return}let p=presets();p[reg]={dow:dow,doi:doi,updated:new Date().toISOString()};savePresets(p);el('reg').value=reg;refreshPresetList();el('presetSelect').value=reg;setText('presetMsg','Preset saved/updated for '+reg+'. Verify after hangar release.');calc()}
function loadPreset(){let reg=el('presetSelect').value;if(!reg)return;let p=presets()[reg];if(!p)return;setv('reg',reg);setv('dow',p.dow);setv('doi',p.doi);setText('presetMsg','Loaded '+reg+'. Verify DOW/DOI with current aircraft document.');calc()}
function deletePreset(){let reg=el('presetSelect').value||el('reg').value.trim().toUpperCase();if(!reg){setText('presetMsg','Select a preset to delete.');return}let p=presets();if(!p[reg]){setText('presetMsg','No preset found for '+reg+'.');return}delete p[reg];savePresets(p);refreshPresetList();setText('presetMsg','Deleted preset '+reg+'.');calc()}
function buildRows(){let root=el('rows');root.innerHTML='';const names=['A','B','C'];for(let r=0;r<5;r++){let row=document.createElement('div');row.className='row';row.innerHTML='<div class="rt"><div class="rowName"><b>Row '+(r+1)+'</b><small>'+(r===0?'Front':r===4?'Rear':'')+'</small></div><em id="rt'+r+'">0 lb</em></div><div class="seats"></div>';let wrap=row.querySelector('.seats');for(let s=0;s<3;s++){let seat=document.createElement('div');seat.className='seat';seat.innerHTML='<div class="sn">'+names[s]+'</div><div class="choices"></div>';let chs=seat.querySelector('.choices');['M','F','C','E'].forEach(k=>{let c=document.createElement('div');c.className='ch';c.dataset.r=r;c.dataset.s=s;c.dataset.v=k;c.textContent=T[k];c.onclick=function(){seats[r][s]=k;suggestedSeats=null;render();calc()};chs.appendChild(c)});wrap.appendChild(seat)}root.appendChild(row)}}
function render(){document.querySelectorAll('.ch').forEach(c=>c.classList.toggle('on',seats[+c.dataset.r][+c.dataset.s]===c.dataset.v));for(let r=0;r<5;r++)setText('rt'+r,f(seats[r].reduce((a,k)=>a+W[k],0))+' lb')}
function updateCgStatus(ok,msg){let box=el('cgStatusBox');let title=el('cgStatusTitle');if(box){box.classList.toggle('statusGood',ok);box.classList.toggle('statusBad',!ok)}if(title)title.textContent=ok?'CG CHECK OK':'CG CHECK WARNING';setText('warn',msg)}
function metricsForSeatMap(map){let dow=n('dow'),doi=n('doi'),block=n('block'),trip=n('trip');let pr=map.map(row=>row.reduce((a,k)=>a+W[k],0));let pax=pr.reduce((a,b)=>a+b,0),pm=pr.reduce((a,w,i)=>a+w*arms[i],0);let st=n('stretcher');pax+=st;pm+=st*224.7;let bd=n('bagD'),ba=n('bagAft'),bs=n('bagShelf'),br5=n('bagR5'),br4=n('bagR4');let bag=bd+ba+bs+br5+br4,bm=bd*302+ba*354+bs*391+br5*254+br4*225;let payload=pax+bag,zfw=dow+payload,tof=block>0?block-50:0,lf=tof-trip,tow=zfw+tof,lw=tow-trip;let dm=0;if(dow>0){let da=(((doi-10)*10000)/dow)+210;dm=da*dow}function cg(w,fuel){let m=dm+pm+bm+fuel*201.7,arm=w?m/w:0;return{arm:arm,index:(((arm-210)*w)/10000)+10,mac:((arm-207.74)*1.282)+25}}return{tow,lw,lf,to:cg(tow,tof),la:cg(lw,lf),rowWeights:pr}}
function scoreSeatMap(map){let m=metricsForSeatMap(map);let score=0;if(n('dow')<=0)score+=100000;if(n('doi')===0)score+=100000;if(n('block')<=0)score+=50000;if(m.tow>12500)score+=(m.tow-12500)*200+50000;if(m.lf<0)score+=Math.abs(m.lf)*200+50000;[m.to.mac,m.la.mac].forEach(mac=>{if(!isFinite(mac))score+=999999;else{if(mac<16)score+=(16-mac)*5000+50000;if(mac>44)score+=(mac-44)*5000+50000;score+=Math.abs(mac-30)*20}});let rw=m.rowWeights;let used=rw.filter(x=>x>0);if(used.length){let avg=used.reduce((a,b)=>a+b,0)/used.length;score+=rw.reduce((a,w)=>a+Math.abs(w-avg)*0.08,0)}return{score,metrics:m}}
function listFromDetected(){let m=parseInt(el('scanMale')?.value||0,10)||0,fm=parseInt(el('scanFemale')?.value||0,10)||0,c=parseInt(el('scanChild')?.value||0,10)||0;let list=[];for(let i=0;i<m;i++)list.push('M');for(let i=0;i<fm;i++)list.push('F');for(let i=0;i<c;i++)list.push('C');return list.slice(0,15)}
function mapFromFlat(flat){let out=emptySeats.map(r=>r.slice());for(let i=0;i<Math.min(15,flat.length);i++){out[Math.floor(i/3)][i%3]=flat[i]}return out}
function seededShuffle(arr,seed){let a=arr.slice();for(let i=a.length-1;i>0;i--){seed=(seed*9301+49297)%233280;let j=Math.floor((seed/233280)*(i+1));let t=a[i];a[i]=a[j];a[j]=t}return a}
function suggestBestSeating(){let list=listFromDetected();let total=(parseInt(el('scanMale')?.value||0,10)||0)+(parseInt(el('scanFemale')?.value||0,10)||0)+(parseInt(el('scanChild')?.value||0,10)||0);if(!total){alert('Scan or enter passenger counts first.');return}let status=el('scanStatus');if(total>15&&status)status.textContent='Only 15 seats are available. Suggesting seating for first 15 pax from detected counts; review/correct manually.';let base=list.slice(0,15);while(base.length<15)base.push('E');let candidates=[];candidates.push(base.slice());candidates.push(base.slice().reverse());candidates.push(base.slice().sort((a,b)=>W[b]-W[a]));candidates.push(base.slice().sort((a,b)=>W[a]-W[b]));let pattern=[6,7,8,3,4,5,9,10,11,0,1,2,12,13,14];let sorted=base.slice().sort((a,b)=>W[b]-W[a]);let patterned=Array(15).fill('E');pattern.forEach((pos,i)=>patterned[pos]=sorted[i]||'E');candidates.push(patterned);for(let s=1;s<=700;s++)candidates.push(seededShuffle(base,s));let best=null;for(let flat of candidates){let map=mapFromFlat(flat);let res=scoreSeatMap(map);if(!best||res.score<best.score)best={map,score:res.score,metrics:res.metrics}}suggestedSeats=best.map.map(r=>r.slice());let b=el('applySuggestedSeatsBtn');if(b)b.disabled=false;let msg='Suggested seating ready. Takeoff %MAC '+f(best.metrics.to.mac,2)+'%, Landing %MAC '+f(best.metrics.la.mac,2)+'%. Review before applying.';if(status)status.textContent=msg;else alert(msg)}
function applySuggestedSeating(){if(!suggestedSeats){alert('Tap Suggest Best Seating first.');return}seats=suggestedSeats.map(r=>r.slice());render();calc();let status=el('scanStatus');if(status)status.textContent='Suggested seating applied. Review passenger positions and CG results before use.'}
function addSeatingSuggestionButtons(){let scanBox=document.querySelector('.scanBox .btns');if(!scanBox||el('suggestSeatsBtn'))return;let s=document.createElement('button');s.id='suggestSeatsBtn';s.type='button';s.className='ghost';s.textContent='Suggest Best Seating';s.onclick=suggestBestSeating;let a=document.createElement('button');a.id='applySuggestedSeatsBtn';a.type='button';a.className='ghost';a.textContent='Apply Suggested Seating';a.disabled=true;a.onclick=applySuggestedSeating;scanBox.appendChild(s);scanBox.appendChild(a)}
function calc(){let reg=(el('reg').value||'').trim().toUpperCase();let dow=n('dow'),doi=n('doi'),block=n('block'),trip=n('trip');let pr=seats.map(row=>row.reduce((a,k)=>a+W[k],0));let paxCount=seats.flat().filter(k=>k!=='E').length;let pax=pr.reduce((a,b)=>a+b,0),pm=pr.reduce((a,w,i)=>a+w*arms[i],0);let avg=paxCount?pax/paxCount:0;let st=n('stretcher');pax+=st;pm+=st*224.7;let aA=pr[0]+pr[1],aB=pr[2]+pr[3],aC=pr[4]+st;let bd=n('bagD'),ba=n('bagAft'),bs=n('bagShelf'),br5=n('bagR5'),br4=n('bagR4');let bag=bd+ba+bs+br5+br4,bm=bd*302+ba*354+bs*391+br5*254+br4*225;let payload=pax+bag,zfw=dow+payload,tof=block>0?block-50:0,lf=tof-trip,tow=zfw+tof,lw=tow-trip;let dm=0;if(dow>0){let da=(((doi-10)*10000)/dow)+210;dm=da*dow}function cg(w,fuel){let m=dm+pm+bm+fuel*201.7,arm=w?m/w:0;return{arm:arm,index:(((arm-210)*w)/10000)+10,mac:((arm-207.74)*1.282)+25}}let to=cg(tow,tof),la=cg(lw,lf);setText('paxTotal',f(pax)+' lb');setText('paxWeightTop',f(pax)+' lb');setText('paxCount',f(paxCount)+' pax');setText('paxCountTop',f(paxCount)+' pax');setText('avgWeight',f(avg)+' lb');setText('areas',f(aA)+' / '+f(aB)+' / '+f(aC));setText('paxMoment',f(pm));setText('doiDisplay',f(doi,2));setText('dowMini',f(dow)+' lb');setText('regMini',reg||'—');setText('blockMini',f(block)+' lb');setText('bagTotal',f(bag)+' lb');setText('payload',f(payload)+' lb');setText('zfw',f(zfw)+' lb');setText('remain',f(12500-tow)+' lb');setText('tof',f(tof)+' lb');setText('tow',f(tow)+' lb');setText('toArm',f(to.arm,2));setText('toIndex',f(to.index,4));setText('toMac',f(to.mac,2)+'%');setText('lf',f(lf)+' lb');setText('lw',f(lw)+' lb');setText('laArm',f(la.arm,2));setText('laIndex',f(la.index,4));setText('laMac',f(la.mac,2)+'%');let remainBox=el('underloadBox');if(remainBox){remainBox.classList.toggle('dangerBox',tow>12500);remainBox.classList.toggle('goodBox',tow>0&&tow<=12500)}let w=[];if(dow<=0)w.push('Enter aircraft Dry Operating Weight and Index.');if(dow>12500)w.push('DOW looks unrealistic for DHC-6. Check extra zeros.');if(doi===0)w.push('Dry Operating Index is zero/missing.');if(block<=0)w.push('Enter block fuel.');if(tow>12500)w.push('Takeoff weight is above 12,500 lb.');if(lf<0)w.push('Landing fuel is negative.');if(tow<=12500&&12500-tow<100&&tow>0)w.push('Close to 12,500 lb limit.');let ok=w.length===0;updateCgStatus(ok, ok?'Complete and within basic weight checks. Verify CG envelope against approved data.':w.join(' '));}
function resetSample(){seats=emptySeats.map(r=>r.slice());suggestedSeats=null;Object.keys(D).forEach(id=>setv(id,D[id]));render();calc();setText('presetMsg','Cleared flight values. Presets are kept saved.')}
function clearSeats(){seats=emptySeats.map(r=>r.slice());suggestedSeats=null;render();calc()}
function applyPassengerList(list){let flat=list.slice(0,15);seats=emptySeats.map(r=>r.slice());let i=0;for(let r=0;r<5;r++){for(let s=0;s<3;s++){if(flat[i])seats[r][s]=flat[i];i++}}suggestedSeats=null;render();calc();return {applied:flat.length,overflow:Math.max(0,list.length-15)}}
window.applyPassengerList=applyPassengerList;window.suggestBestSeating=suggestBestSeating;window.applySuggestedSeating=applySuggestedSeating;
window.addEventListener('DOMContentLoaded',function(){buildRows();resetSample();refreshPresetList();addSeatingSuggestionButtons();setText('badge','Offline Ready');el('resetBtn').textContent='New Flight';el('resetBtn').onclick=resetSample;el('clearBtn').onclick=clearSeats;el('savePresetBtn').onclick=savePreset;el('loadPresetBtn').onclick=loadPreset;el('deletePresetBtn').onclick=deletePreset;el('presetSelect').onchange=loadPreset;document.querySelectorAll('input').forEach(i=>i.oninput=function(){suggestedSeats=null;let b=el('applySuggestedSeatsBtn');if(b)b.disabled=true;calc()});if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});