const W={E:0,M:189,F:150,C:77},T={E:'–',M:'M',F:'F',C:'C'},arms=[135,165,195,225,254];
const emptySeats=[['E','E','E'],['E','E','E'],['E','E','E'],['E','E','E'],['E','E','E']];
const D={reg:'',dow:0,doi:0,block:0,trip:0,stretcher:0,bagD:0,bagAft:0,bagShelf:0,bagR5:0,bagR4:0};
const PRESET_KEY='dhc6_aircraft_presets_v1';
let seats=emptySeats.map(r=>r.slice()),suggestedSeats=null;
function el(id){return document.getElementById(id)}
function n(id){let x=el(id),v=x?parseFloat(x.value):0;return isFinite(v)?v:0}
function f(x,d=0){return Number(x||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d})}
function setv(id,v){let x=el(id);if(x){x.value=String(v);x.defaultValue=String(v)}}
function setText(id,t){let x=el(id);if(x)x.textContent=t}
function presets(){try{return JSON.parse(localStorage.getItem(PRESET_KEY)||'{}')}catch(e){return{}}}
function savePresets(p){localStorage.setItem(PRESET_KEY,JSON.stringify(p))}
function refreshPresetList(){let s=el('presetSelect');if(!s)return;let p=presets(),cur=s.value;s.innerHTML='<option value="">Select aircraft preset</option>';Object.keys(p).sort().forEach(r=>{let o=document.createElement('option');o.value=r;o.textContent=r+' — DOW '+p[r].dow+' / DOI '+p[r].doi;s.appendChild(o)});if(p[cur])s.value=cur}
function savePreset(){let r=(el('reg').value||'').trim().toUpperCase(),dow=n('dow'),doi=n('doi');if(!r)return setText('presetMsg','Enter aircraft registration first.');if(dow<=0||doi===0)return setText('presetMsg','Enter current DOW and DOI before saving preset.');if(dow>12500)return setText('presetMsg','DOW looks too high for DHC-6. Check extra zeros before saving preset.');let p=presets();p[r]={dow,doi,updated:new Date().toISOString()};savePresets(p);el('reg').value=r;refreshPresetList();el('presetSelect').value=r;setText('presetMsg','Preset saved/updated for '+r+'. Verify after hangar release.');calc()}
function loadPreset(){let r=el('presetSelect').value,p=presets()[r];if(!p)return;setv('reg',r);setv('dow',p.dow);setv('doi',p.doi);setText('presetMsg','Loaded '+r+'. Verify DOW/DOI with current aircraft document.');calc()}
function deletePreset(){let r=el('presetSelect').value||(el('reg').value||'').trim().toUpperCase();if(!r)return setText('presetMsg','Select a preset to delete.');let p=presets();if(!p[r])return setText('presetMsg','No preset found for '+r+'.');delete p[r];savePresets(p);refreshPresetList();setText('presetMsg','Deleted preset '+r+'.');calc()}
function buildRows(){let root=el('rows');if(!root)return;root.innerHTML='';['1','2','3','4','5'].forEach((_,r)=>{let row=document.createElement('div');row.className='row';row.innerHTML='<div class="rt"><div class="rowName"><b>Row '+(r+1)+'</b><small>'+(r===0?'Front':r===4?'Rear':'')+'</small></div><em id="rt'+r+'">0 lb</em></div><div class="seats"></div>';let wrap=row.querySelector('.seats');['A','B','C'].forEach((name,s)=>{let seat=document.createElement('div');seat.className='seat';seat.innerHTML='<div class="sn">'+name+'</div><div class="choices"></div>';let chs=seat.querySelector('.choices');['M','F','C','E'].forEach(k=>{let c=document.createElement('div');c.className='ch';c.dataset.r=r;c.dataset.s=s;c.dataset.v=k;c.textContent=T[k];c.onclick=()=>{seats[r][s]=k;suggestedSeats=null;render();calc()};chs.appendChild(c)});wrap.appendChild(seat)});root.appendChild(row)})}
function render(){document.querySelectorAll('.ch').forEach(c=>c.classList.toggle('on',seats[+c.dataset.r][+c.dataset.s]===c.dataset.v));for(let r=0;r<5;r++)setText('rt'+r,f(seats[r].reduce((a,k)=>a+W[k],0))+' lb')}
function updateCgStatus(ok,msg){let b=el('cgStatusBox'),t=el('cgStatusTitle');if(b){b.classList.toggle('statusGood',ok);b.classList.toggle('statusBad',!ok)}if(t)t.textContent=ok?'CG CHECK OK':'CG CHECK WARNING';setText('warn',msg)}
function metricsForSeatMap(map){let dow=n('dow'),doi=n('doi'),block=n('block'),trip=n('trip'),pr=map.map(r=>r.reduce((a,k)=>a+W[k],0));let pax=pr.reduce((a,b)=>a+b,0),pm=pr.reduce((a,w,i)=>a+w*arms[i],0),st=n('stretcher');pax+=st;pm+=st*224.7;let bd=n('bagD'),ba=n('bagAft'),bs=n('bagShelf'),br5=n('bagR5'),br4=n('bagR4');let bag=bd+ba+bs+br5+br4,bm=bd*302+ba*354+bs*391+br5*254+br4*225,payload=pax+bag,zfw=dow+payload,tof=block>0?block-50:0,lf=tof-trip,tow=zfw+tof,lw=tow-trip;let dm=0;if(dow>0){let da=(((doi-10)*10000)/dow)+210;dm=da*dow}function cg(w,fuel){let m=dm+pm+bm+fuel*201.7,arm=w?m/w:0;return{arm,index:(((arm-210)*w)/10000)+10,mac:((arm-207.74)*1.282)+25}}return{pr,pax,pm,bag,bm,payload,zfw,tof,lf,tow,lw,to:cg(tow,tof),la:cg(lw,lf)}}
function scoreSeatMap(map){let m=metricsForSeatMap(map),score=0;if(n('dow')<=0)score+=100000;if(n('doi')===0)score+=100000;if(n('block')<=0)score+=50000;if(m.tow>12500)score+=(m.tow-12500)*200+50000;if(m.lf<0)score+=Math.abs(m.lf)*200+50000;[m.to.mac,m.la.mac].forEach(mac=>{if(!isFinite(mac))score+=999999;else{if(mac<16)score+=(16-mac)*5000+50000;if(mac>44)score+=(mac-44)*5000+50000;score+=Math.abs(mac-30)*20}});let used=m.pr.filter(x=>x>0);if(used.length){let avg=used.reduce((a,b)=>a+b,0)/used.length;score+=m.pr.reduce((a,w)=>a+Math.abs(w-avg)*0.08,0)}return{score,metrics:m}}
function listFromDetected(){let m=parseInt(el('scanMale')?.value||0)||0,fm=parseInt(el('scanFemale')?.value||0)||0,c=parseInt(el('scanChild')?.value||0)||0,list=[];for(let i=0;i<m;i++)list.push('M');for(let i=0;i<fm;i++)list.push('F');for(let i=0;i<c;i++)list.push('C');return list.slice(0,15)}
function mapFromFlat(flat){let out=emptySeats.map(r=>r.slice());for(let i=0;i<Math.min(15,flat.length);i++)out[Math.floor(i/3)][i%3]=flat[i];return out}
function seededShuffle(arr,seed){let a=arr.slice();for(let i=a.length-1;i>0;i--){seed=(seed*9301+49297)%233280;let j=Math.floor((seed/233280)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function suggestBestSeating(){let list=listFromDetected(),total=(parseInt(el('scanMale')?.value||0)||0)+(parseInt(el('scanFemale')?.value||0)||0)+(parseInt(el('scanChild')?.value||0)||0),status=el('scanStatus');if(!total){alert('Scan or enter passenger counts first.');return}if(total>15&&status)status.textContent='Only 15 seats are available. Suggesting seating for first 15 pax from detected counts; review/correct manually.';let base=list.slice(0,15);while(base.length<15)base.push('E');let candidates=[base.slice(),base.slice().reverse(),base.slice().sort((a,b)=>W[b]-W[a]),base.slice().sort((a,b)=>W[a]-W[b])];let pattern=[6,7,8,3,4,5,9,10,11,0,1,2,12,13,14],sorted=base.slice().sort((a,b)=>W[b]-W[a]),pat=Array(15).fill('E');pattern.forEach((pos,i)=>pat[pos]=sorted[i]||'E');candidates.push(pat);for(let s=1;s<=700;s++)candidates.push(seededShuffle(base,s));let best=null;for(let flat of candidates){let map=mapFromFlat(flat),res=scoreSeatMap(map);if(!best||res.score<best.score)best={map,score:res.score,metrics:res.metrics}}suggestedSeats=best.map.map(r=>r.slice());let b=el('applySuggestedSeatsBtn');if(b)b.disabled=false;let msg='Suggested seating ready. Takeoff %MAC '+f(best.metrics.to.mac,2)+'%, Landing %MAC '+f(best.metrics.la.mac,2)+'%. Review before applying.';status?status.textContent=msg:alert(msg)}
function applySuggestedSeating(){if(!suggestedSeats){alert('Tap Suggest Best Seating first.');return}seats=suggestedSeats.map(r=>r.slice());render();calc();let s=el('scanStatus');if(s)s.textContent='Suggested seating applied. Review passenger positions and CG results before use.'}
function addSeatingSuggestionButtons(){let box=document.querySelector('.scanBox .btns');if(!box||el('suggestSeatsBtn'))return;let s=document.createElement('button');s.id='suggestSeatsBtn';s.type='button';s.className='ghost';s.textContent='Suggest Best Seating';s.onclick=suggestBestSeating;let a=document.createElement('button');a.id='applySuggestedSeatsBtn';a.type='button';a.className='ghost';a.textContent='Apply Suggested Seating';a.disabled=true;a.onclick=applySuggestedSeating;box.appendChild(s);box.appendChild(a)}
function calc(){let reg=(el('reg')?.value||'').trim().toUpperCase(),m=metricsForSeatMap(seats),paxCount=seats.flat().filter(k=>k!=='E').length,avg=paxCount?m.pax/paxCount:0;let aA=m.pr[0],aB=m.pr[1]+m.pr[2],aC=m.pr[3]+m.pr[4];setText('paxTotal',f(m.pax)+' lb');setText('paxWeightTop',f(m.pax)+' lb');setText('paxCount',f(paxCount)+' pax');setText('paxCountTop',f(paxCount)+' pax');setText('avgWeight',f(avg)+' lb');setText('areas',f(aA)+' / '+f(aB)+' / '+f(aC));setText('paxMoment',f(m.pm));setText('doiDisplay',f(n('doi'),2));setText('dowMini',f(n('dow'))+' lb');setText('regMini',reg||'—');setText('blockMini',f(n('block'))+' lb');setText('bagTotal',f(m.bag)+' lb');setText('payload',f(m.payload)+' lb');setText('zfw',f(m.zfw)+' lb');setText('remain',f(12500-m.tow)+' lb');setText('tof',f(m.tof)+' lb');setText('tow',f(m.tow)+' lb');setText('toArm',f(m.to.arm,2));setText('toIndex',f(m.to.index,4));setText('toMac',f(m.to.mac,2)+'%');setText('lf',f(m.lf)+' lb');setText('lw',f(m.lw)+' lb');setText('laArm',f(m.la.arm,2));setText('laIndex',f(m.la.index,4));setText('laMac',f(m.la.mac,2)+'%');let rb=el('underloadBox');if(rb){rb.classList.toggle('dangerBox',m.tow>12500);rb.classList.toggle('goodBox',m.tow>0&&m.tow<=12500)}let w=[];if(n('dow')<=0)w.push('Enter aircraft Dry Operating Weight and Index.');if(n('dow')>12500)w.push('DOW looks unrealistic for DHC-6. Check extra zeros.');if(n('doi')===0)w.push('Dry Operating Index is zero/missing.');if(n('block')<=0)w.push('Enter block fuel.');if(m.tow>12500)w.push('Takeoff weight is above 12,500 lb.');if(m.lf<0)w.push('Landing fuel is negative.');if(m.tow<=12500&&12500-m.tow<100&&m.tow>0)w.push('Close to 12,500 lb limit.');updateCgStatus(w.length===0,w.length?'Complete and within basic weight checks. Verify CG envelope against approved data.':w.join(' '));if(w.length)updateCgStatus(false,w.join(' '))}
function resetSample(){seats=emptySeats.map(r=>r.slice());suggestedSeats=null;Object.keys(D).forEach(id=>setv(id,D[id]));render();calc();setText('presetMsg','Cleared flight values. Presets are kept saved.')}
function clearSeats(){seats=emptySeats.map(r=>r.slice());suggestedSeats=null;render();calc()}
function applyPassengerList(list){let flat=list.slice(0,15);seats=emptySeats.map(r=>r.slice());let i=0;for(let r=0;r<5;r++)for(let s=0;s<3;s++){if(flat[i])seats[r][s]=flat[i];i++}suggestedSeats=null;render();calc();return{applied:flat.length,overflow:Math.max(0,list.length-15)}}
window.applyPassengerList=applyPassengerList;window.suggestBestSeating=suggestBestSeating;window.applySuggestedSeating=applySuggestedSeating;
window.addEventListener('DOMContentLoaded',()=>{buildRows();resetSample();refreshPresetList();addSeatingSuggestionButtons();setText('badge','Offline Ready');el('resetBtn').textContent='New Flight';el('resetBtn').onclick=resetSample;el('clearBtn').onclick=clearSeats;el('savePresetBtn').onclick=savePreset;el('loadPresetBtn').onclick=loadPreset;el('deletePresetBtn').onclick=deletePreset;el('presetSelect').onchange=loadPreset;document.querySelectorAll('input').forEach(i=>i.oninput=()=>{suggestedSeats=null;let b=el('applySuggestedSeatsBtn');if(b)b.disabled=true;calc()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});