function scanEl(id){return document.getElementById(id)}
function getScanInt(id){let v=parseInt(scanEl(id)?.value,10);return Number.isFinite(v)&&v>0?v:0}
function setScanStatus(msg){let s=scanEl('scanStatus');if(s)s.textContent=msg}
function setScanProgress(msg){let s=scanEl('scanProgress');if(s)s.textContent=msg||''}
function normalizeOcr(text){return(text||'').replace(/\r/g,'\n').replace(/[~–—]/g,'-').replace(/[|]/g,'I').replace(/[ \t]+/g,' ').trim()}
function sanePax(v){v=parseInt(String(v).replace(/[^0-9]/g,''),10);return Number.isFinite(v)&&v>=0&&v<=999?v:null}
function installScannerCSS(){
  if(document.getElementById('scannerCleanCss'))return;
  let st=document.createElement('style');
  st.id='scannerCleanCss';
  st.textContent=`
  .scannerDrop{border-color:rgba(22,199,183,.35)!important;background:linear-gradient(135deg,rgba(22,199,183,.09),rgba(32,167,255,.055)),rgba(255,255,255,.035)!important}
  .scannerDrop>summary{justify-content:center!important;text-align:center!important;position:relative;padding:15px 48px!important;letter-spacing:.8px;background:linear-gradient(135deg,rgba(22,199,183,.12),rgba(32,167,255,.07));border-bottom:1px solid rgba(180,230,255,.10)}
  .scannerDrop>summary:after{position:absolute;right:18px;top:50%;transform:translateY(-50%)}
  .scannerCompact{display:grid;gap:13px}.scannerTop{display:grid;grid-template-columns:1fr;gap:8px}.scanBtnWrap{display:flex;flex-direction:column;gap:6px}.scanProgress{font-size:12px;color:#ffe39c;min-height:18px;text-align:center;font-weight:800}.scanPrimary{width:100%;background:rgba(255,255,255,.08)!important}.scannerActions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.scannerActions button{width:100%}.scannerActions .wide{grid-column:1/-1}.suggestGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.suggestGrid button{width:100%}.scannerCounts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.scannerCounts input{font-size:18px}.scanTotalBox{grid-column:1/-1;border:1px solid rgba(22,199,183,.45);border-radius:16px;background:linear-gradient(135deg,rgba(22,199,183,.16),rgba(32,167,255,.08));padding:10px}.scanTotalBox label{text-align:center;color:#dff8ff;font-weight:900;letter-spacing:.5px}.scanTotalBox input{text-align:center;font-size:26px;font-weight:950;border-color:rgba(22,199,183,.35)}.ocrToggle{font-size:12px;color:#9ab5c0;border-top:1px solid rgba(180,230,255,.10);padding-top:8px}.ocrToggle summary{text-align:center;font-weight:900;color:#dff8ff;cursor:pointer}.scanBox{background:linear-gradient(135deg,rgba(255,200,87,.06),rgba(22,199,183,.06)),rgba(255,255,255,.035)!important;border-color:rgba(22,199,183,.28)!important}.scanBox .miniNote{margin:0;text-align:center;color:#ffe39c;font-size:12px;line-height:1.45}.scanBox label{text-align:left}.scanStatusClean{text-align:center;margin:0!important}
  @media(max-width:420px){.scannerActions,.suggestGrid{grid-template-columns:1fr}.scannerCounts{grid-template-columns:1fr 1fr}.scanTotalBox{grid-column:1/-1}}
  `;
  document.head.appendChild(st)
}
function rebuildScannerUI(){
  let box=document.querySelector('.scanBox');
  if(!box||box.dataset.cleanUi==='1')return;
  let details=box.closest('details');
  if(details){details.classList.add('scannerDrop');let sm=details.querySelector('summary');if(sm)sm.textContent='Manifest Scanner Beta'}
  box.dataset.cleanUi='1';
  box.innerHTML=`<div class="scannerCompact"><p class="miniNote">OCR can misread. Review counts before applying.</p><div class="scannerTop"><div><label>Take photo / upload manifest</label><input id="manifestFile" type="file" accept="image/*"></div><div class="scanBtnWrap"><button id="scanBtn" class="ghost scanPrimary" type="button">Scan Manifest</button><div id="scanProgress" class="scanProgress"></div></div></div><div class="scannerActions"><button id="applyScanBtn" class="ghost" type="button">Apply Detected Passengers</button><button id="clearScanBtn" class="danger" type="button">Clear Scan</button></div><div class="suggestGrid"><button id="suggestSeatsBtn" class="ghost" type="button">Suggest Best Seating</button><button id="applySuggestedSeatsBtn" class="ghost" type="button">Apply Suggested Seating</button></div><div class="scannerCounts"><div><label>Male</label><input id="scanMale" type="number" value="0"></div><div><label>Female</label><input id="scanFemale" type="number" value="0"></div><div><label>Child</label><input id="scanChild" type="number" value="0"></div><div><label>Unclear</label><input id="scanUnknown" type="number" value="0"></div><div class="scanTotalBox"><label>Total Pax</label><input id="scanTotal" type="number" value="0"></div></div><p id="scanStatus" class="note warn scanStatusClean">Choose from camera or photo library, then scan.</p><details class="ocrToggle"><summary>OCR text</summary><textarea id="ocrText" placeholder="OCR result will appear here for review"></textarea></details></div>`
}
function parseManifestTotal(raw){let text=normalizeOcr(raw).toUpperCase();let patterns=[/CABIN\s+TOTAL\s+PAX\s*[:\-]?\s*0*(\d{1,3})/i,/TOTAL\s+PAX\s*[:\-]?\s*0*(\d{1,3})/i,/TTL\s+0*([0-9]{1,3})\s+PAX/i,/PAX\s*[:\-]?\s*0*(\d{1,3})/i];for(let re of patterns){let m=text.match(re);if(m){let v=sanePax(m[1]);if(v!==null&&v>0)return v}}return 0}
function parseCheckedInValue(raw,label){let lines=normalizeOcr(raw).split(/\n+/).map(x=>x.trim()).filter(Boolean),labelRe=new RegExp('^\\s*'+label+'\\b','i'),checkedRe=/(CHECKED[ -]?IN\/?BOARDED|CHECKED[ -]?IN|BOARDED)/i;for(let line of lines){if(!labelRe.test(line)||!checkedRe.test(line))continue;let nums=line.match(/\d{1,3}/g)||[];if(nums.length){let v=sanePax(nums[nums.length-1]);if(v!==null)return v}}let flat=normalizeOcr(raw).toUpperCase(),re=new RegExp('(?:^|[^A-Z])'+label+'\\b[^\n]{0,80}?(?:CHECKED[ -]?IN\\/?BOARDED|CHECKED[ -]?IN|BOARDED)\\s*[-:=]?\\s*(\\d{1,3})','i'),m=flat.match(re);if(m){let v=sanePax(m[1]);if(v!==null)return v}return null}
function parseManifestedValue(raw,label){let lines=normalizeOcr(raw).split(/\n+/).map(x=>x.trim()).filter(Boolean),labelRe=new RegExp('^\\s*'+label+'\\b','i');for(let line of lines){if(!labelRe.test(line)||!/MANIFESTED/i.test(line))continue;let nums=line.match(/\d{1,3}/g)||[];if(nums.length){let v=sanePax(nums[0]);if(v!==null)return v}}return null}
function parseZoneTotals(raw){let lines=normalizeOcr(raw).toUpperCase().split(/\n+/).map(x=>x.trim()).filter(Boolean);for(let line of lines){if(!/^TOTALS\s*[:]?/.test(line))continue;let nums=(line.match(/\d{1,4}/g)||[]).map(x=>parseInt(x,10));if(nums.length>=3){let male=nums[0],female=nums[1],child=nums[2],total=nums[3]||male+female+child;if(male<=300&&female<=300&&child<=100&&Math.abs((male+female+child)-total)<=5)return{male,female,child,source:'zone totals'}}}return null}
function parsePassengerListTitles(raw){let text=normalizeOcr(raw).toUpperCase(),male=0,female=0,child=0,unknown=0,hasPassengerList=/PASSENGER\s+LIST|FARE\s+SEQ\s+SEAT|TOTAL\/SEG\/CL|CLASS\s+[A-Z]|MLE\s+MANIFEST/i.test(text),lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),passengerId='(?:\\d{3,4}|[0O]\\d{1,3}|OSS|OS8|O1|OT|V7|I68)';lines.forEach(line=>{if(/PASSENGER LIST|TOTAL\/SEG|FARE SEQ|CLASS |ACFT REGN|MALD(I|1)VIAN|MALAYSIA AIRLINES|PAGE|FLIGHT INFO|STATUS|COMMENT|CABIN TOTAL|TOTAL PAX|ETD/.test(line))return;let chunks=[],re=new RegExp('([A-Z\\[\\] \\/_+]+?)\\s*'+passengerId+'(?:\\s|$)','gi'),m;while((m=re.exec(line))!==null){let chunk=(m[1]||'').trim();if(chunk.includes('/'))chunks.push(chunk)}if(!chunks.length&&line.includes('/'))chunks=[line];chunks.forEach(chunk=>{let normalized=chunk.replace(/_/g,' ').replace(/\+/g,' ').replace(/\bM R\b/g,' MR').replace(/\bM RS\b/g,' MRS').replace(/\bM S\b/g,' MS').replace(/\bM STR\b/g,' MSTR').replace(/[^A-Z\/ ]/g,' ').replace(/\s+/g,' ').trim(),last=(normalized.split('/').pop()||normalized).replace(/\s+/g,'').trim();if(/(MSTR|MASTER|CHD|CHILD)$/.test(last)||/\b(MSTR|MASTER|CHD|CHILD)\b/.test(normalized)){child++;return}if(/(MRS|MISS|MS)$/.test(last)||/\b(MRS|MISS|MS)\b/.test(normalized)){female++;return}if(/(MR)$/.test(last)||/\bMR\b/.test(normalized)){male++;return}if(/\+$/.test(chunk)||chunk.includes('+'))unknown++})});let total=male+female+child;if(total>0&&(hasPassengerList||total>=5))return{male,female,child,unknown,source:'passenger list titles'};return null}
function parseSimpleCounts(raw){let text=normalizeOcr(raw);function explicit(label){let lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),re=new RegExp('^\\s*'+label+'\\b\\s*[:=\\-]?\\s*(\\d{1,3})','i');for(let line of lines){let m=line.match(re);if(m){let v=sanePax(m[1]);if(v!==null)return v}}return 0}let male=explicit('MALE'),female=explicit('FEMALE'),child=explicit('CHILD|CHD|CHILDREN');if(male||female||child)return{male,female,child,unknown:0,source:'simple totals'};return{male:0,female:0,child:0,unknown:0,source:'no counts found'}}
function parseManifestCounts(text){let raw=(text||'').replace(/\r/g,'\n'),total=parseManifestTotal(raw),child=parseCheckedInValue(raw,'CHILD'),female=parseCheckedInValue(raw,'FEMALE'),male=parseCheckedInValue(raw,'MALE');if(male!==null||female!==null||child!==null)return{male:male||0,female:female||0,child:child||0,unknown:0,total,source:'checked-in/boarded totals'};let zone=parseZoneTotals(raw);if(zone)return Object.assign({unknown:0,total},zone);child=parseManifestedValue(raw,'CHILD');female=parseManifestedValue(raw,'FEMALE');male=parseManifestedValue(raw,'MALE');if(male!==null||female!==null||child!==null)return{male:male||0,female:female||0,child:child||0,unknown:0,total,source:'manifested totals'};let titleCounts=parsePassengerListTitles(raw);if(titleCounts)return Object.assign({total},titleCounts);return Object.assign({total},parseSimpleCounts(raw))}
async function runManifestOCR(){let input=scanEl('manifestFile');if(!input||!input.files||!input.files[0]){setScanStatus('Choose or take a manifest photo first.');return}if(!window.Tesseract){setScanStatus('OCR engine not loaded. Internet may be needed the first time.');return}setScanStatus('Scanning manifest…');setScanProgress('Starting…');try{let result=await Tesseract.recognize(input.files[0],'eng',{logger:m=>{if(m.status){let msg='OCR: '+m.status+(m.progress?' '+Math.round(m.progress*100)+'%':'');setScanProgress(msg)}}}),text=result&&result.data&&result.data.text?result.data.text:'';scanEl('ocrText').value=text.trim();let c=parseManifestCounts(text);scanEl('scanMale').value=c.male;scanEl('scanFemale').value=c.female;scanEl('scanChild').value=c.child;scanEl('scanUnknown').value=c.unknown||0;scanEl('scanTotal').value=c.total||((c.male||0)+(c.female||0)+(c.child||0)+(c.unknown||0));setScanProgress('Done');setScanStatus('Detected '+c.male+' male, '+c.female+' female, '+c.child+' child'+((c.unknown||0)?', '+c.unknown+' unclear':'')+'. Review before applying.')}catch(e){console.error(e);setScanProgress('Failed');setScanStatus('OCR failed. Try a clearer photo or enter counts manually.')}}
function applyScannedPassengers(){let m=getScanInt('scanMale'),f=getScanInt('scanFemale'),c=getScanInt('scanChild'),u=getScanInt('scanUnknown'),t=getScanInt('scanTotal'),list=[];for(let i=0;i<m;i++)list.push('M');for(let i=0;i<f;i++)list.push('F');for(let i=0;i<c;i++)list.push('C');if(!window.applyPassengerList){setScanStatus('Seat fill function not ready. Refresh page.');return}let r=window.applyPassengerList(list),msg='Applied '+r.applied+' passengers to seats.';if(r.overflow)msg+=' '+r.overflow+' passenger(s) did not fit in 15 seats.';if(t&&(m+f+c+u)!==t)msg+=' Total mismatch: '+t+' total vs '+(m+f+c)+' classified + '+u+' unclear.';if(u)msg+=' '+u+' unclear passenger(s) were not seated automatically.';setScanStatus(msg)}
function clearScan(){['scanMale','scanFemale','scanChild','scanUnknown','scanTotal'].forEach(id=>{let x=scanEl(id);if(x)x.value=0});if(scanEl('ocrText'))scanEl('ocrText').value='';if(scanEl('manifestFile'))scanEl('manifestFile').value='';setScanProgress('');setScanStatus('Scanner cleared.')}
window.addEventListener('DOMContentLoaded',function(){installScannerCSS();rebuildScannerUI();let b=scanEl('scanBtn');if(b)b.onclick=runManifestOCR;let a=scanEl('applyScanBtn');if(a)a.onclick=applyScannedPassengers;let c=scanEl('clearScanBtn');if(c)c.onclick=clearScan;let s=scanEl('suggestSeatsBtn');if(s)s.onclick=()=>window.suggestBestSeating&&window.suggestBestSeating();let as=scanEl('applySuggestedSeatsBtn');if(as)as.onclick=()=>window.applySuggestedSeating&&window.applySuggestedSeating()});